'use client';

import React from 'react';
import Link from 'next/link';
import { ArrowLeft, Shield } from 'lucide-react';

function Logo() {
  return (
    <Link href="/" className="logo">
      <div className="brand-mark">
        <span />
      </div>
      <span>BRANDFORGE</span>
    </Link>
  );
}

export default function PrivacyPage() {
  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', color: 'var(--fg)', display: 'flex', flexDirection: 'column' }}>
      <header
        style={{
          borderBottom: '1px solid var(--border)',
          padding: '16px 32px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          background: 'rgba(12, 13, 16, 0.85)',
          backdropFilter: 'blur(10px)',
          position: 'sticky',
          top: 0,
          zIndex: 40,
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: '20px' }}>
          <Logo />
          <div style={{ height: '18px', width: '1px', background: 'var(--border)' }} />
          <Link
            href="/"
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              color: 'var(--muted)',
              fontSize: '12px',
              textDecoration: 'none',
            }}
          >
            <ArrowLeft size={14} /> Back to BrandForge
          </Link>
        </div>
      </header>

      <main style={{ maxWidth: '800px', width: '100%', margin: '0 auto', padding: '60px 24px 80px' }}>
        <div className="eyebrow" style={{ marginBottom: '12px' }}>
          <span className="eyebrow-line" /> TRUST & DATA GOVERNANCE
        </div>
        <h1 style={{ fontFamily: 'Georgia, serif', fontSize: '38px', margin: '0 0 16px', fontWeight: 500, letterSpacing: '-0.04em' }}>
          Privacy Policy
        </h1>
        <p style={{ color: 'var(--muted)', fontSize: '13px', marginBottom: '40px', lineHeight: 1.6 }}>
          Last updated: September 2026 • BrandForge AI Brand Intelligence Studio
        </p>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '32px', lineHeight: 1.7, fontSize: '14px', color: '#c5c7d0' }}>
          <section>
            <h2 style={{ fontFamily: 'Georgia, serif', fontSize: '20px', color: '#fff', margin: '0 0 12px', fontWeight: 500 }}>
              1. Our Data Commitment
            </h2>
            <p>
              BrandForge is built for founders, creators, and teams developing new intellectual property. We treat your startup ideas, positioning strategies, naming explorations, and visual concepts as strictly confidential private business information. We do not sell your personal data or your brand ideas.
            </p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'Georgia, serif', fontSize: '20px', color: '#fff', margin: '0 0 12px', fontWeight: 500 }}>
              2. Information We Collect
            </h2>
            <ul style={{ paddingLeft: '20px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <li><strong>Account Credentials:</strong> Name, work email address, and encrypted credentials managed via Supabase Auth.</li>
              <li><strong>Brand Data & Prompts:</strong> Business concept descriptions, target audiences, industry categories, tags, and constraints entered into the studio workflow.</li>
              <li><strong>Generated Artifacts:</strong> Positioning statements, naming shortlists, visual palettes, critiques, and launch kits generated by our 8-stage AI agent graph.</li>
              <li><strong>Technical Metadata:</strong> System timestamps, rate-limiting tokens, error logs, and privacy-preserving workflow analytics.</li>
            </ul>
          </section>

          <section>
            <h2 style={{ fontFamily: 'Georgia, serif', fontSize: '20px', color: '#fff', margin: '0 0 12px', fontWeight: 500 }}>
              3. AI Processing & Third-Party LLM Providers
            </h2>
            <p>
              BrandForge orchestrates specialized AI agents using enterprise APIs (such as OpenAI, Anthropic, or Google Gemini). We only transmit data to AI providers operating under enterprise terms with explicit agreements that customer data is <strong>never used to train public foundation models</strong>.
            </p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'Georgia, serif', fontSize: '20px', color: '#fff', margin: '0 0 12px', fontWeight: 500 }}>
              4. Storage & Tenant Isolation
            </h2>
            <p>
              All customer projects and generated assets are stored in Supabase PostgreSQL and Supabase Private Storage with PostgreSQL Row-Level Security (RLS). No user can access or view another user&apos;s brand projects, chat history, or export files unless explicitly made public through a share link generated by the owner.
            </p>
          </section>

          <section>
            <h2 style={{ fontFamily: 'Georgia, serif', fontSize: '20px', color: '#fff', margin: '0 0 12px', fontWeight: 500 }}>
              5. Data Retention & Deletion Rights
            </h2>
            <p>
              You maintain complete ownership of your data. You may delete individual projects or request a complete purge of your studio account at any time via the Settings page or by contacting <code>privacy@brandforge.ai</code>. Upon deletion, all associated database records, vector state, and PDF export files are permanently removed.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
