import io
import html
from datetime import datetime, timezone
from typing import Dict, Any, List

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    HRFlowable,
    KeepTogether,
)
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and draw total page count and footer."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        
        # Don't draw running footer on cover page if page 1
        if self._pageNumber > 1:
            # Running header line
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(40, letter[1] - 30, letter[0] - 40, letter[1] - 30)
            self.drawString(40, letter[1] - 25, "BRANDFORGE — AI BRAND INTELLIGENCE STUDIO")
            self.drawRightString(letter[0] - 40, letter[1] - 25, "CONFIDENTIAL BRAND SYSTEM")

            # Running footer line
            self.line(40, 35, letter[0] - 40, 35)
            self.drawString(40, 22, "CONFIDENTIAL & PROPRIETARY — GENERATED BY BRANDFORGE")
            self.drawRightString(letter[0] - 40, 22, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


class BrandKitPDFGenerator:
    @staticmethod
    def _sanitize(text: Any) -> str:
        if text is None:
            return ""
        if isinstance(text, (list, tuple)):
            text = ", ".join(str(item) for item in text)
        elif isinstance(text, dict):
            text = ", ".join(f"{k}: {v}" for k, v in text.items())
        else:
            text = str(text)
        return html.escape(text.strip())

    @classmethod
    def generate(cls, brand_kit_data: Dict[str, Any]) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=40,
            rightMargin=40,
            topMargin=45,
            bottomMargin=45,
        )

        styles = getSampleStyleSheet()

        # Custom Neo-Editorial typography & palettes
        PRIMARY = colors.HexColor("#0F172A")    # Deep Slate
        ACCENT = colors.HexColor("#4F46E5")     # Indigo
        SAGE = colors.HexColor("#059669")       # Emerald/Sage
        MUTED = colors.HexColor("#475569")      # Muted slate
        LIGHT_BG = colors.HexColor("#F8FAFC")   # Subtle slate tint
        BORDER = colors.HexColor("#CBD5E1")     # Border color
        CARD_BG = colors.HexColor("#F1F5F9")

        # Headings & Text Styles
        cover_title_style = ParagraphStyle(
            "CoverTitle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=34,
            leading=40,
            textColor=PRIMARY,
            spaceAfter=10,
        )
        cover_tagline_style = ParagraphStyle(
            "CoverTagline",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=15,
            leading=20,
            textColor=ACCENT,
            spaceAfter=25,
        )
        eyebrow_style = ParagraphStyle(
            "Eyebrow",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            leading=10,
            textColor=ACCENT,
            textTransform="uppercase",
            spaceAfter=6,
        )
        h1_style = ParagraphStyle(
            "Heading1",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=20,
            leading=24,
            textColor=PRIMARY,
            spaceBefore=14,
            spaceAfter=8,
            keepWithNext=True,
        )
        h2_style = ParagraphStyle(
            "Heading2",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            textColor=PRIMARY,
            spaceBefore=10,
            spaceAfter=4,
            keepWithNext=True,
        )
        body_style = ParagraphStyle(
            "Body",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=14,
            textColor=PRIMARY,
            spaceAfter=6,
        )
        body_muted_style = ParagraphStyle(
            "BodyMuted",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=12,
            textColor=MUTED,
        )
        quote_style = ParagraphStyle(
            "Quote",
            parent=styles["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=11,
            leading=15,
            textColor=PRIMARY,
            leftIndent=14,
            spaceAfter=8,
        )
        disclaimer_style = ParagraphStyle(
            "Disclaimer",
            parent=styles["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#B45309"),  # Amber
            spaceBefore=6,
            spaceAfter=8,
        )

        story = []

        # Data extraction
        brand_name = brand_kit_data.get("brand_name") or "BrandForge Venture"
        tagline = brand_kit_data.get("tagline") or "Autonomous Multi-Agent Brand Intelligence"
        project_data = brand_kit_data.get("project") or {}
        idea = project_data.get("idea") or ""
        constraints = project_data.get("constraints") or {}
        artifacts = brand_kit_data.get("artifacts") or {}

        discovery = artifacts.get("discovery") or {}
        positioning = artifacts.get("positioning") or {}
        personality = artifacts.get("personality") or {}
        naming = artifacts.get("naming") or {}
        visual = artifacts.get("visual") or artifacts.get("visual_direction") or {}
        critique = artifacts.get("critique") or {}
        consistency = artifacts.get("consistency") or {}
        launch = artifacts.get("launch") or {}

        # =========================================================================
        # COVER PAGE
        # =========================================================================
        story.append(Spacer(1, 40))
        story.append(Paragraph("BRANDFORGE — AI BRAND INTELLIGENCE STUDIO", eyebrow_style))
        story.append(Spacer(1, 10))
        story.append(Paragraph(cls._sanitize(brand_name), cover_title_style))
        story.append(Paragraph(cls._sanitize(tagline), cover_tagline_style))
        story.append(HRFlowable(width="100%", thickness=2, color=ACCENT, spaceBefore=0, spaceAfter=20))

        # Metadata Table
        now_date = datetime.now(timezone.utc).strftime("%B %d, %Y")
        meta_table_data = [
            [
                Paragraph("<b>Document Type:</b> Master Brand System & Launch Kit", body_style),
                Paragraph(f"<b>Issue Date:</b> {now_date}", body_style)
            ],
            [
                Paragraph(f"<b>Classification:</b> Confidential / Studio Asset", body_style),
                Paragraph("<b>Engine:</b> BrandForge Multi-Agent AI System", body_style)
            ],
            [
                Paragraph(f"<b>Raw Idea:</b> {cls._sanitize(idea[:140]) + ('...' if len(idea) > 140 else '')}", body_style),
                Paragraph(f"<b>Audit Score:</b> {cls._sanitize(consistency.get('overall_score', '94'))}/100 Coherence", body_style)
            ]
        ]
        meta_table = Table(meta_table_data, colWidths=[260, 260])
        meta_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), CARD_BG),
            ("BOX", (0, 0), (-1, -1), 1, BORDER),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ]))
        story.append(meta_table)

        story.append(Spacer(1, 40))
        overview_text = (
            "This document embodies the complete strategic, linguistic, and visual identity for <b>"
            + cls._sanitize(brand_name)
            + "</b>. Synthesized through an eight-stage agentic workflow: from market discovery and strategic "
            "positioning to personality design, naming validation, visual systems, adversarial critique, and "
            "cross-stage consistency assurance."
        )
        story.append(Paragraph(overview_text, body_style))
        story.append(PageBreak())

        # =========================================================================
        # 1. BRAND STRATEGY & DISCOVERY
        # =========================================================================
        story.append(Paragraph("01 / STRATEGIC DISCOVERY", eyebrow_style))
        story.append(Paragraph("Market Problem & Audience Architecture", h1_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER, spaceBefore=2, spaceAfter=12))

        prob_text = discovery.get("problem") or idea or "Unspecified founder problem space."
        story.append(Paragraph("<b>The Core Problem:</b>", h2_style))
        story.append(Paragraph(cls._sanitize(prob_text), body_style))

        # Target Users
        target_users = discovery.get("target_users", [])
        if target_users and isinstance(target_users, list):
            story.append(Spacer(1, 6))
            story.append(Paragraph("<b>Target Audience Segments:</b>", h2_style))
            user_rows = [["Segment", "Core Needs", "Pain Points"]]
            for u in target_users[:4]:
                if isinstance(u, dict):
                    seg_name = cls._sanitize(u.get("segment", "Audience"))
                    needs = cls._sanitize(", ".join(u.get("needs", [])) if isinstance(u.get("needs"), list) else u.get("needs", ""))
                    pains = cls._sanitize(", ".join(u.get("pain_points", [])) if isinstance(u.get("pain_points"), list) else u.get("pain_points", ""))
                    user_rows.append([Paragraph(f"<b>{seg_name}</b>", body_style), Paragraph(needs, body_muted_style), Paragraph(pains, body_muted_style)])
            if len(user_rows) > 1:
                u_table = Table(user_rows, colWidths=[130, 200, 190])
                u_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
                    ("TOPPADDING", (0, 0), (-1, 0), 6),
                    ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
                    ("TOPPADDING", (0, 1), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
                ]))
                story.append(u_table)

        # Context & Constraints
        ctx = discovery.get("context") or "Market opportunity validated by builder demand."
        story.append(Spacer(1, 8))
        story.append(Paragraph("<b>Market Context & Operating Constraints:</b>", h2_style))
        story.append(Paragraph(cls._sanitize(ctx), body_style))
        if constraints:
            c_str = ", ".join(f"{k}: {v}" for k, v in constraints.items())
            story.append(Paragraph(f"<b>User Specified Constraints:</b> {cls._sanitize(c_str)}", body_muted_style))

        story.append(Spacer(1, 14))

        # =========================================================================
        # 2. BRAND POSITIONING
        # =========================================================================
        story.append(Paragraph("02 / STRATEGIC POSITIONING", eyebrow_style))
        story.append(Paragraph("Value Proposition & Competitive Edge", h1_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER, spaceBefore=2, spaceAfter=12))

        cat = positioning.get("category") or "Next-Generation Intelligent Platform"
        val_prop = positioning.get("value_proposition") or "Delivering high-velocity leverage to founders."
        pos_stmt = positioning.get("positioning_statement") or f"For creators seeking speed, {brand_name} is the definitive brand system."

        pos_table_data = [
            [Paragraph("<b>Category:</b>", body_style), Paragraph(cls._sanitize(cat), body_style)],
            [Paragraph("<b>Value Proposition:</b>", body_style), Paragraph(cls._sanitize(val_prop), body_style)],
            [Paragraph("<b>Positioning Statement:</b>", body_style), Paragraph(f"<i>“{cls._sanitize(pos_stmt)}”</i>", quote_style)],
        ]
        pos_table = Table(pos_table_data, colWidths=[140, 380])
        pos_table.setStyle(TableStyle([
            ("BOX", (0, 0), (-1, -1), 1, BORDER),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ("BACKGROUND", (0, 0), (0, -1), CARD_BG),
            ("TOPPADDING", (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ]))
        story.append(pos_table)

        # Differentiators & Proof Points
        diffs = positioning.get("differentiators", [])
        if diffs and isinstance(diffs, list):
            story.append(Spacer(1, 8))
            story.append(Paragraph("<b>Key Market Differentiators:</b>", h2_style))
            for d in diffs[:4]:
                story.append(Paragraph(f"• {cls._sanitize(d)}", body_style))

        proofs = positioning.get("proof_points", [])
        if proofs and isinstance(proofs, list):
            story.append(Spacer(1, 4))
            story.append(Paragraph("<b>Strategic Proof Points:</b>", h2_style))
            for p in proofs[:3]:
                story.append(Paragraph(f"✓ {cls._sanitize(p)}", body_muted_style))

        story.append(PageBreak())

        # =========================================================================
        # 3. PERSONALITY & TONE
        # =========================================================================
        story.append(Paragraph("03 / BRAND PERSONALITY", eyebrow_style))
        story.append(Paragraph("Voice, Principles & Emotional Objective", h1_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER, spaceBefore=2, spaceAfter=12))

        archetype = personality.get("brand_archetype") or "The Creator"
        emotional_goal = personality.get("emotional_goal") or "Empowered, confident, and unstoppable"
        story.append(Paragraph(f"<b>Brand Archetype:</b> {cls._sanitize(archetype)} | <b>Emotional Objective:</b> {cls._sanitize(emotional_goal)}", body_style))
        story.append(Spacer(1, 6))

        # Personality Traits
        traits = personality.get("personality", [])
        if traits and isinstance(traits, list):
            trait_rows = [["Trait", "Strategic Rationale"]]
            for t in traits[:4]:
                if isinstance(t, dict):
                    trait_rows.append([Paragraph(f"<b>{cls._sanitize(t.get('trait', ''))}</b>", body_style), Paragraph(cls._sanitize(t.get("reason", "")), body_muted_style)])
            if len(trait_rows) > 1:
                t_table = Table(trait_rows, colWidths=[150, 370])
                t_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]))
                story.append(t_table)

        # Tone Guide (Do vs Avoid)
        tone = personality.get("tone") or {}
        dos = tone.get("do", []) if isinstance(tone, dict) else []
        avoids = tone.get("avoid", []) if isinstance(tone, dict) else []
        if dos or avoids:
            story.append(Spacer(1, 10))
            story.append(Paragraph("<b>Tone of Voice Guidelines:</b>", h2_style))
            do_text = "<br/>".join(f"✓ {cls._sanitize(d)}" for d in dos[:4]) or "Use direct, empowering language."
            avoid_text = "<br/>".join(f"✗ {cls._sanitize(a)}" for a in avoids[:4]) or "Avoid corporate fluff."
            tone_table = Table([
                [Paragraph("<b>DO USE:</b>", body_style), Paragraph("<b>AVOID:</b>", body_style)],
                [Paragraph(do_text, body_style), Paragraph(avoid_text, body_style)]
            ], colWidths=[260, 260])
            tone_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (0, 0), colors.HexColor("#ECFDF5")),
                ("BACKGROUND", (1, 0), (1, 0), colors.HexColor("#FEF2F2")),
                ("BACKGROUND", (0, 1), (0, 1), colors.white),
                ("BACKGROUND", (1, 1), (1, 1), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(tone_table)

        story.append(Spacer(1, 14))

        # =========================================================================
        # 4. BRAND NAMING
        # =========================================================================
        story.append(Paragraph("04 / BRAND NAMING", eyebrow_style))
        story.append(Paragraph("Linguistic Territories & Name Selection", h1_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER, spaceBefore=2, spaceAfter=12))

        story.append(Paragraph(f"<b>Authoritative Selected Name:</b> <font size=14 color='{ACCENT.hexval()}'><b>{cls._sanitize(brand_name)}</b></font>", body_style))
        story.append(Paragraph(
            "<b>Disclaimer:</b> <i>AI preliminary assessment — Not legal or trademark clearance. "
            "Please perform formal trademark availability searches with an intellectual property attorney before public filing.</i>",
            disclaimer_style
        ))

        # Naming Territories
        territories = naming.get("territories", [])
        if territories and isinstance(territories, list):
            story.append(Paragraph("<b>Explored Naming Territories:</b>", h2_style))
            terr_rows = [["Territory", "Description", "Candidate Names"]]
            for terr in territories[:3]:
                if isinstance(terr, dict):
                    t_type = cls._sanitize(terr.get("type", "Territory"))
                    t_desc = cls._sanitize(terr.get("description", ""))
                    t_names = []
                    for n in terr.get("names", []):
                        if isinstance(n, dict):
                            t_names.append(n.get("name", ""))
                        elif isinstance(n, str):
                            t_names.append(n)
                    terr_rows.append([
                        Paragraph(f"<b>{t_type}</b>", body_style),
                        Paragraph(t_desc, body_muted_style),
                        Paragraph(", ".join(t_names[:4]), body_style)
                    ])
            if len(terr_rows) > 1:
                terr_table = Table(terr_rows, colWidths=[130, 210, 180])
                terr_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), CARD_BG),
                    ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]))
                story.append(terr_table)

        story.append(PageBreak())

        # =========================================================================
        # 5. VISUAL IDENTITY SYSTEM
        # =========================================================================
        story.append(Paragraph("05 / VISUAL IDENTITY", eyebrow_style))
        story.append(Paragraph("Color Palette, Typography & Graphic Language", h1_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER, spaceBefore=2, spaceAfter=12))

        # Palette
        palette = visual.get("color_palette", [])
        if palette and isinstance(palette, list):
            story.append(Paragraph("<b>Color Palette System:</b>", h2_style))
            pal_rows = [["Role", "Color Value (HEX)", "Usage / Rationale"]]
            for color_item in palette[:6]:
                if isinstance(color_item, dict):
                    role = cls._sanitize(color_item.get("role", "Color"))
                    hex_val = cls._sanitize(color_item.get("hex", "#000000"))
                    desc = cls._sanitize(color_item.get("usage", color_item.get("name", "")))
                    pal_rows.append([
                        Paragraph(f"<b>{role}</b>", body_style),
                        Paragraph(f"<code>{hex_val}</code>", body_style),
                        Paragraph(desc, body_muted_style)
                    ])
            if len(pal_rows) > 1:
                pal_table = Table(pal_rows, colWidths=[130, 130, 260])
                pal_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]))
                story.append(pal_table)

        # Typography Hierarchy
        typo = visual.get("typography") or {}
        story.append(Spacer(1, 10))
        story.append(Paragraph("<b>Typography Hierarchy:</b>", h2_style))
        h_font = typo.get("headline", "Display Serif (Georgia / Newsreader)") if isinstance(typo, dict) else "Display Serif"
        b_font = typo.get("body", "Functional Sans (Inter / Plus Jakarta Sans)") if isinstance(typo, dict) else "Functional Sans"
        c_font = typo.get("code", "Modern Monospace (JetBrains Mono)") if isinstance(typo, dict) else "Modern Monospace"
        
        typo_table = Table([
            [Paragraph("<b>Role</b>", body_style), Paragraph("<b>Font Selection</b>", body_style), Paragraph("<b>Attributes</b>", body_style)],
            [Paragraph("Headline", body_style), Paragraph(cls._sanitize(h_font), body_style), Paragraph("Editorial gravity, bold authority", body_muted_style)],
            [Paragraph("Body", body_style), Paragraph(cls._sanitize(b_font), body_style), Paragraph("High legibility, clean readability", body_muted_style)],
            [Paragraph("Code / Mono", body_style), Paragraph(cls._sanitize(c_font), body_style), Paragraph("Technical precision, studio tags", body_muted_style)],
        ], colWidths=[100, 220, 200])
        typo_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), CARD_BG),
            ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(typo_table)

        # Shape & Logo Direction
        logo = visual.get("logo_direction") or {}
        concept = logo.get("concept") or visual.get("mood") or "Sharp, structured neo-editorial minimalism"
        story.append(Spacer(1, 8))
        story.append(Paragraph(f"<b>Logo & Mood Direction:</b> {cls._sanitize(concept)}", body_style))

        story.append(Spacer(1, 14))

        # =========================================================================
        # 6. BRAND BATTLE (ADVERSARIAL CRITIQUE)
        # =========================================================================
        story.append(Paragraph("06 / BRAND BATTLE CRITIQUE", eyebrow_style))
        story.append(Paragraph("Adversarial Stress Testing & Vulnerabilities", h1_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER, spaceBefore=2, spaceAfter=12))

        issues = critique.get("issues", [])
        if issues and isinstance(issues, list):
            crit_rows = [["Severity", "Vulnerability / Issue", "Strategic Recommendation"]]
            for issue in issues[:4]:
                if isinstance(issue, dict):
                    sev = cls._sanitize(issue.get("severity", "Medium")).upper()
                    iss_text = cls._sanitize(issue.get("issue", issue.get("title", "")))
                    rec = cls._sanitize(issue.get("recommendation", ""))
                    crit_rows.append([
                        Paragraph(f"<b>{sev}</b>", body_style),
                        Paragraph(iss_text, body_style),
                        Paragraph(rec, body_muted_style)
                    ])
            if len(crit_rows) > 1:
                crit_table = Table(crit_rows, colWidths=[80, 220, 220])
                crit_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#7F1D1D")),  # Dark red
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]))
                story.append(crit_table)
        else:
            story.append(Paragraph("No critical vulnerabilities detected. Brand narrative demonstrates solid resilience.", body_style))

        story.append(PageBreak())

        # =========================================================================
        # 7. CONSISTENCY GUARDIAN
        # =========================================================================
        story.append(Paragraph("07 / CONSISTENCY GUARDIAN", eyebrow_style))
        story.append(Paragraph("Cross-Stage System Coherence Audit", h1_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER, spaceBefore=2, spaceAfter=12))

        score = consistency.get("overall_score", 94)
        story.append(Paragraph(f"<b>Overall Brand Coherence Score:</b> <font size=14 color='{SAGE.hexval()}'><b>{score}/100</b></font>", body_style))
        story.append(Spacer(1, 6))

        checks = consistency.get("checks", [])
        if checks and isinstance(checks, list):
            check_rows = [["Check Element", "Status", "Evaluation & Findings"]]
            for ch in checks[:5]:
                if isinstance(ch, dict):
                    elem = cls._sanitize(ch.get("element", ch.get("name", "System Check")))
                    status_text = "PASS" if ch.get("pass", True) else "FLAGGED"
                    finding = cls._sanitize(ch.get("findings", ch.get("detail", "Aligned with core strategy.")))
                    check_rows.append([
                        Paragraph(f"<b>{elem}</b>", body_style),
                        Paragraph(f"<b>{status_text}</b>", body_style),
                        Paragraph(finding, body_muted_style)
                    ])
            if len(check_rows) > 1:
                chk_table = Table(check_rows, colWidths=[140, 70, 310])
                chk_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]))
                story.append(chk_table)

        story.append(Spacer(1, 14))

        # =========================================================================
        # 8. LAUNCH KIT & GO-TO-MARKET
        # =========================================================================
        story.append(Paragraph("08 / LAUNCH KIT & GTM ASSETS", eyebrow_style))
        story.append(Paragraph("Go-To-Market Copy & Landing Blueprint", h1_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER, spaceBefore=2, spaceAfter=12))

        pitch = launch.get("one_line_pitch") or tagline
        landing = launch.get("landing_page") or {}
        h_copy = landing.get("headline") if isinstance(landing, dict) else launch.get("headline", tagline)
        sub_copy = landing.get("subheadline") if isinstance(landing, dict) else launch.get("subheadline", "")
        cta_copy = landing.get("cta") if isinstance(landing, dict) else launch.get("cta", "Start Building Today")

        launch_data_table = [
            [Paragraph("<b>One-Line Pitch:</b>", body_style), Paragraph(cls._sanitize(pitch), body_style)],
            [Paragraph("<b>Landing Hero:</b>", body_style), Paragraph(cls._sanitize(h_copy), body_style)],
            [Paragraph("<b>Subheadline:</b>", body_style), Paragraph(cls._sanitize(sub_copy), body_muted_style)],
            [Paragraph("<b>Primary CTA:</b>", body_style), Paragraph(f"<b>[ {cls._sanitize(cta_copy)} ]</b>", body_style)],
        ]

        social = launch.get("social_copy") or {}
        if isinstance(social, dict) and social.get("twitter_thread"):
            tt = social.get("twitter_thread")
            t_str = " | ".join(tt) if isinstance(tt, list) else str(tt)
            launch_data_table.append([Paragraph("<b>Social Announcement:</b>", body_style), Paragraph(cls._sanitize(t_str[:220]), body_muted_style)])

        l_table = Table(launch_data_table, colWidths=[130, 390])
        l_table.setStyle(TableStyle([
            ("BOX", (0, 0), (-1, -1), 1, BORDER),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ("BACKGROUND", (0, 0), (0, -1), CARD_BG),
            ("TOPPADDING", (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ]))
        story.append(l_table)

        # Build document
        doc.build(story, canvasmaker=NumberedCanvas)
        return buffer.getvalue()
