import io
import html
from datetime import datetime, timezone
from typing import Dict, Any, List

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    HRFlowable,
    KeepTogether,
)
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and draw total page count and footer."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        
        # Don't draw running footer on cover page if page 1
        if self._pageNumber > 1:
            # Running header line
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(40, letter[1] - 30, letter[0] - 40, letter[1] - 30)
            self.drawString(40, letter[1] - 25, "BRANDFORGE — AI BRAND INTELLIGENCE STUDIO")
            self.drawRightString(letter[0] - 40, letter[1] - 25, "CONFIDENTIAL BRAND SYSTEM")

            # Running footer line
            self.line(40, 35, letter[0] - 40, 35)
            self.drawString(40, 22, "CONFIDENTIAL & PROPRIETARY — GENERATED BY BRANDFORGE")
            self.drawRightString(letter[0] - 40, 22, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


class BrandKitPDFGenerator:
    @staticmethod
    def _sanitize(text: Any) -> str:
        if text is None:
            return ""
        if isinstance(text, (list, tuple)):
            text = ", ".join(str(item) for item in text)
        elif isinstance(text, dict):
            text = ", ".join(f"{k}: {v}" for k, v in text.items())
        else:
            text = str(text)
        return html.escape(text.strip())

    @classmethod
    def generate(cls, brand_kit_data: Dict[str, Any]) -> bytes:
        """Render the accumulated BrandForge state as a detailed, evidence-traceable brand report."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=42,
            rightMargin=42,
            topMargin=48,
            bottomMargin=48,
        )
        styles = getSampleStyleSheet()

        PRIMARY = colors.HexColor("#0F172A")
        ACCENT = colors.HexColor("#4F46E5")
        SAGE = colors.HexColor("#059669")
        MUTED = colors.HexColor("#475569")
        LIGHT_BG = colors.HexColor("#F8FAFC")
        BORDER = colors.HexColor("#CBD5E1")
        CARD_BG = colors.HexColor("#F1F5F9")
        AMBER = colors.HexColor("#B45309")

        cover_title = ParagraphStyle(
            "BF_CoverTitle", parent=styles["Title"], fontName="Helvetica-Bold",
            fontSize=34, leading=38, textColor=PRIMARY, spaceAfter=12
        )
        eyebrow = ParagraphStyle(
            "BF_Eyebrow", parent=styles["Normal"], fontName="Helvetica-Bold",
            fontSize=8, leading=10, textColor=ACCENT, spaceAfter=7
        )
        h1 = ParagraphStyle(
            "BF_H1", parent=styles["Heading1"], fontName="Helvetica-Bold",
            fontSize=21, leading=25, textColor=PRIMARY, spaceAfter=8
        )
        h2 = ParagraphStyle(
            "BF_H2", parent=styles["Heading2"], fontName="Helvetica-Bold",
            fontSize=12, leading=15, textColor=PRIMARY, spaceBefore=8, spaceAfter=5
        )
        body = ParagraphStyle(
            "BF_Body", parent=styles["BodyText"], fontName="Helvetica",
            fontSize=9.5, leading=14, textColor=PRIMARY, spaceAfter=6
        )
        muted = ParagraphStyle(
            "BF_Muted", parent=body, fontSize=8.5, leading=12, textColor=MUTED
        )
        quote = ParagraphStyle(
            "BF_Quote", parent=body, fontName="Helvetica-Oblique",
            fontSize=11, leading=16, textColor=PRIMARY, leftIndent=12, rightIndent=12
        )
        small = ParagraphStyle(
            "BF_Small", parent=body, fontSize=7.5, leading=10, textColor=MUTED
        )
        callout = ParagraphStyle(
            "BF_Callout", parent=body, fontName="Helvetica-Bold",
            fontSize=10, leading=14, textColor=PRIMARY
        )

        artifacts = brand_kit_data.get("artifacts") or {}
        project = brand_kit_data.get("project") or {}
        selected = brand_kit_data.get("selected_directions") or {}
        if not isinstance(selected, dict):
            selected = {}

        def first_artifact(*keys):
            for key in keys:
                value = artifacts.get(key)
                if isinstance(value, dict) and value:
                    return value
            return {}

        discovery = first_artifact("discovery", "discover")
        positioning = first_artifact("positioning", "position")
        personality = first_artifact("personality", "strategist")
        naming = first_artifact("naming", "name")
        visual = first_artifact("visual", "visual_direction", "creative")
        critique = first_artifact("critique", "critic")
        consistency = first_artifact("consistency", "guardian")
        launch = first_artifact("launch")

        brand_name = cls._sanitize(brand_kit_data.get("brand_name") or "Pending user selection")
        tagline = cls._sanitize(brand_kit_data.get("tagline") or launch.get("tagline") or "Tagline not generated")
        raw_idea = brand_kit_data.get("raw_idea") or project.get("idea") or project.get("description") or project.get("brief") or ""
        constraints = project.get("constraints") or {}

        def val(obj, *keys, default=""):
            if not isinstance(obj, dict):
                return default
            for key in keys:
                v = obj.get(key)
                if v not in (None, ""):
                    return v
            return default

        def as_list(value):
            if value is None:
                return []
            if isinstance(value, list):
                return value
            return [value]

        def bullets(items, style=body, empty="Not generated by the workflow."):
            items = as_list(items)
            if not items:
                return [Paragraph(cls._sanitize(empty), muted)]
            out = []
            for item in items:
                if isinstance(item, dict):
                    text_value = item.get("name") or item.get("description") or item.get("text") or str(item)
                else:
                    text_value = str(item)
                out.append(Paragraph(f"• {cls._sanitize(text_value)}", style))
            return out

        def section(number, title, subtitle=None):
            story.append(Paragraph(f"{number} / {title.upper()}", eyebrow))
            story.append(Paragraph(title, h1))
            if subtitle:
                story.append(Paragraph(cls._sanitize(subtitle), muted))
            story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER, spaceBefore=2, spaceAfter=12))

        def key_value_table(rows):
            data = []
            for label, value in rows:
                data.append([
                    Paragraph(f"<b>{cls._sanitize(label)}</b>", body),
                    Paragraph(cls._sanitize(value if value not in (None, "") else "Not generated by the workflow."), body),
                ])
            table = Table(data, colWidths=[145, 375], repeatRows=0)
            table.setStyle(TableStyle([
                ("BOX", (0, 0), (-1, -1), 0.7, BORDER),
                ("INNERGRID", (0, 0), (-1, -1), 0.35, BORDER),
                ("BACKGROUND", (0, 0), (0, -1), CARD_BG),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 7),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ]))
            story.append(table)

        def bullet_section(title, items):
            story.append(Paragraph(title, h2))
            for item in bullets(items):
                story.append(item)

        story = []

        # ---------------------------------------------------------------------
        # COVER
        # ---------------------------------------------------------------------
        story.append(Spacer(1, 1.0 * inch))
        story.append(Paragraph("BRANDFORGE", eyebrow))
        story.append(Paragraph("AI Brand Intelligence Report", cover_title))
        story.append(Paragraph(brand_name, ParagraphStyle(
            "BF_CoverBrand", parent=cover_title, fontSize=25, leading=30, textColor=ACCENT
        )))
        story.append(Paragraph(f"“{tagline}”", quote))
        story.append(Spacer(1, 24))
        story.append(Paragraph(
            "A detailed synthesis of discovery, positioning, personality, naming, visual direction, "
            "adversarial critique, consistency checks, and launch assets generated by the BrandForge agent pipeline.",
            body
        ))
        story.append(Spacer(1, 18))
        story.append(key_value_table([
            ("Project", project.get("name") or project.get("title") or "Brand project"),
            ("Pipeline", "8-agent brand intelligence workflow"),
            ("Report status", brand_kit_data.get("status") or "completed"),
            ("Generated", datetime.now(timezone.utc).strftime("%d %b %Y, %H:%M UTC")),
        ]))
        story.append(Spacer(1, 20))
        story.append(Paragraph(
            "Important: AI-generated strategy is a working decision system, not market validation, legal advice, "
            "or trademark clearance. Claims marked as assumptions or open questions should be validated by the founder.",
            small
        ))
        story.append(PageBreak())

        # ---------------------------------------------------------------------
        # 01 EXECUTIVE SUMMARY
        # ---------------------------------------------------------------------
        section("01", "Executive Brand Summary", "The current strategic spine of the brand.")
        story.append(Paragraph("Authoritative Brand Name", h2))
        story.append(Paragraph(brand_name, ParagraphStyle(
            "BF_Name", parent=cover_title, fontSize=22, leading=26, textColor=ACCENT
        )))
        key_value_table([
            ("Tagline", tagline),
            ("Core problem", val(discovery, "problem", default="Not generated by the workflow.")),
            ("Category", val(positioning, "category", default="Not generated by the workflow.")),
            ("Value proposition", val(positioning, "value_proposition", default="Not generated by the workflow.")),
            ("Positioning statement", val(positioning, "positioning_statement", default="Not generated by the workflow.")),
            ("Brand archetype", val(personality, "brand_archetype", default="Not generated by the workflow.")),
            ("Emotional goal", val(personality, "emotional_goal", default="Not generated by the workflow.")),
        ])
        story.append(Spacer(1, 10))
        story.append(Paragraph("Strategic Through-Line", h2))
        story.append(Paragraph(
            "The report should be read as a chain: the discovered problem and audience create the positioning; "
            "positioning shapes personality and naming; personality and positioning shape the visual system; "
            "critique and consistency testing pressure-test the system; the launch agent turns the approved system into execution.",
            body
        ))
        story.append(PageBreak())

        # ---------------------------------------------------------------------
        # 02 DISCOVERY
        # ---------------------------------------------------------------------
        section("02", "Discovery & Problem Definition", "What the workflow understood from the founder's original brief.")
        story.append(Paragraph("Original Brief", h2))
        story.append(Paragraph(
            cls._sanitize(raw_idea or "No raw idea was stored with the export payload."),
            quote
        ))
        story.append(Paragraph("Core Problem", h2))
        story.append(Paragraph(
            cls._sanitize(val(discovery, "problem", default="Not generated by the workflow.")),
            body
        ))
        story.append(Paragraph("Market / Operating Context", h2))
        story.append(Paragraph(
            cls._sanitize(val(discovery, "context", default="Not generated by the workflow.")),
            body
        ))
        bullet_section("Goals", discovery.get("goals", []))
        bullet_section("Explicit Constraints", discovery.get("constraints", []))
        bullet_section("Assumptions", discovery.get("assumptions", []))
        bullet_section("Open Questions Requiring Validation", discovery.get("open_questions", []))
        if constraints:
            bullet_section("Founder-Supplied Project Constraints", [
                f"{k}: {v}" for k, v in constraints.items()
            ])
        story.append(PageBreak())

        # ---------------------------------------------------------------------
        # 03 AUDIENCE
        # ---------------------------------------------------------------------
        section("03", "Audience & Customer Fit", "Audience segments, needs, and pain points identified by discovery.")
        segments = discovery.get("target_users", [])
        if segments:
            rows = [[
                Paragraph("<b>Segment</b>", body),
                Paragraph("<b>Needs</b>", body),
                Paragraph("<b>Pain Points</b>", body),
            ]]
            for seg in segments:
                if isinstance(seg, dict):
                    rows.append([
                        Paragraph(f"<b>{cls._sanitize(seg.get('segment', 'Audience segment'))}</b>", body),
                        Paragraph("<br/>".join(f"• {cls._sanitize(x)}" for x in as_list(seg.get("needs"))), muted),
                        Paragraph("<br/>".join(f"• {cls._sanitize(x)}" for x in as_list(seg.get("pain_points"))), muted),
                    ])
            table = Table(rows, colWidths=[130, 195, 195], repeatRows=1)
            table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 7),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ]))
            story.append(table)
        else:
            story.append(Paragraph("No structured audience segments were generated.", muted))
        story.append(Spacer(1, 14))
        story.append(Paragraph("Audience Implication", h2))
        story.append(Paragraph(
            "These segments are the evidence base available to the later agents. Where discovery lists an open question "
            "or assumption, the brand team should treat the related audience claim as provisional rather than established fact.",
            body
        ))
        story.append(PageBreak())

        # ---------------------------------------------------------------------
        # 04 POSITIONING
        # ---------------------------------------------------------------------
        section("04", "Strategic Positioning", "How the concept is framed in the market.")
        key_value_table([
            ("Category", val(positioning, "category", default="Not generated by the workflow.")),
            ("Core problem", val(positioning, "core_problem", default="Not generated by the workflow.")),
            ("Value proposition", val(positioning, "value_proposition", default="Not generated by the workflow.")),
            ("Competitive angle", val(positioning, "competitive_angle", default="Not generated by the workflow.")),
            ("Positioning statement", val(positioning, "positioning_statement", default="Not generated by the workflow.")),
        ])
        bullet_section("Differentiators", positioning.get("differentiators", []))
        bullet_section("Proof Points / Claims to Validate", positioning.get("proof_points", []))
        story.append(PageBreak())

        # ---------------------------------------------------------------------
        # 05 PERSONALITY + VOICE
        # ---------------------------------------------------------------------
        section("05", "Brand Personality & Voice", "The behavioral system that should govern communication.")
        key_value_table([
            ("Archetype", val(personality, "brand_archetype", default="Not generated by the workflow.")),
            ("Emotional goal", val(personality, "emotional_goal", default="Not generated by the workflow.")),
        ])
        traits = personality.get("personality", [])
        if traits:
            story.append(Paragraph("Personality Traits & Strategic Reasons", h2))
            rows = [[Paragraph("<b>Trait</b>", body), Paragraph("<b>Reason</b>", body)]]
            for item in traits:
                if isinstance(item, dict):
                    rows.append([
                        Paragraph(f"<b>{cls._sanitize(item.get('trait', 'Trait'))}</b>", body),
                        Paragraph(cls._sanitize(item.get("reason", "")), muted),
                    ])
            table = Table(rows, colWidths=[145, 375], repeatRows=1)
            table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(table)
        tone = personality.get("tone") or {}
        story.append(Spacer(1, 10))
        story.append(Paragraph("Tone of Voice — DO", h2))
        story.extend(bullets(tone.get("do", [])))
        story.append(Paragraph("Tone of Voice — AVOID", h2))
        story.extend(bullets(tone.get("avoid", [])))
        bullet_section("Brand Principles", personality.get("principles", []))
        story.append(PageBreak())

        # ---------------------------------------------------------------------
        # 06 NAMING
        # ---------------------------------------------------------------------
        section("06", "Naming System", "Territories, candidates, rationale, strengths, and risks.")
        story.append(Paragraph("Authoritative Selection", h2))
        story.append(Paragraph(brand_name, ParagraphStyle(
            "BF_Selected", parent=cover_title, fontSize=19, leading=23, textColor=ACCENT
        )))
        story.append(Paragraph(
            "User-selected names are authoritative. If no selection was available, the report uses an AI-generated candidate "
            "only as a provisional recommendation. No name in this report represents legal or trademark clearance.",
            small
        ))
        territories = naming.get("territories", [])
        for idx, territory in enumerate(territories, start=1):
            if not isinstance(territory, dict):
                continue
            story.append(Paragraph(
                f"{idx}. {cls._sanitize(territory.get('type', 'Naming Territory'))}",
                h2
            ))
            story.append(Paragraph(cls._sanitize(territory.get("description", "")), body))
            candidates = territory.get("names", [])
            if candidates:
                rows = [[
                    Paragraph("<b>Candidate</b>", body),
                    Paragraph("<b>Rationale</b>", body),
                    Paragraph("<b>Strengths</b>", body),
                    Paragraph("<b>Risks</b>", body),
                ]]
                for candidate in candidates:
                    if isinstance(candidate, dict):
                        rows.append([
                            Paragraph(f"<b>{cls._sanitize(candidate.get('name', ''))}</b>", body),
                            Paragraph(cls._sanitize(candidate.get("rationale", "")), muted),
                            Paragraph("<br/>".join(f"• {cls._sanitize(x)}" for x in as_list(candidate.get("strengths"))), muted),
                            Paragraph("<br/>".join(f"• {cls._sanitize(x)}" for x in as_list(candidate.get("risks"))), muted),
                        ])
                table = Table(rows, colWidths=[90, 170, 130, 130], repeatRows=1)
                table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), CARD_BG),
                    ("GRID", (0, 0), (-1, -1), 0.35, BORDER),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ]))
                story.append(table)
                story.append(Spacer(1, 7))
        if not territories:
            story.append(Paragraph("No naming territories were generated.", muted))
        story.append(PageBreak())

        # ---------------------------------------------------------------------
        # 07 VISUAL IDENTITY
        # ---------------------------------------------------------------------
        section("07", "Visual Identity System", "A practical design direction derived from the strategic artifacts.")
        vd = visual.get("visual_direction") if isinstance(visual.get("visual_direction"), dict) else visual
        bullet_section("Mood", vd.get("mood", []))
        colors_data = vd.get("color_direction") or vd.get("color_palette") or []
        story.append(Paragraph("Color Direction", h2))
        if colors_data:
            for color_item in colors_data:
                if isinstance(color_item, dict):
                    role = color_item.get("role") or color_item.get("name") or "Color"
                    hex_value = color_item.get("hex") or color_item.get("value") or ""
                    usage = color_item.get("usage") or color_item.get("description") or ""
                    story.append(Paragraph(
                        f"<b>{cls._sanitize(role)}</b> — {cls._sanitize(hex_value)} — {cls._sanitize(usage)}",
                        body
                    ))
                else:
                    story.append(Paragraph(f"• {cls._sanitize(color_item)}", body))
        else:
            story.append(Paragraph("No color direction was generated.", muted))
        bullet_section("Typography", vd.get("typography", []))
        bullet_section("Composition / Layout", vd.get("composition", []))
        bullet_section("Shape Language", vd.get("shape_language", []))
        bullet_section("Imagery Direction", vd.get("imagery", []))
        bullet_section("Symbol Concepts", vd.get("symbol_concepts", []))
        bullet_section("Avoid / Clichés", vd.get("avoid", []))
        logo = visual.get("logo_direction") if isinstance(visual, dict) else {}
        if isinstance(logo, dict):
            story.append(Paragraph("Logo Direction", h2))
            story.append(Paragraph(
                f"<b>Concept:</b> {cls._sanitize(logo.get('concept', 'Not generated.'))}<br/>"
                f"<b>Rationale:</b> {cls._sanitize(logo.get('rationale', 'Not generated.'))}",
                body
            ))
        story.append(PageBreak())

        # ---------------------------------------------------------------------
        # 08 BRAND BATTLE
        # ---------------------------------------------------------------------
        section("08", "Brand Battle Critique", "Adversarial stress testing performed before final synthesis.")
        issues = critique.get("issues", [])
        if issues:
            rows = [[
                Paragraph("<b>Severity</b>", body),
                Paragraph("<b>Area / Target</b>", body),
                Paragraph("<b>Problem & Evidence</b>", body),
                Paragraph("<b>Suggested Action</b>", body),
            ]]
            for issue in issues:
                if isinstance(issue, dict):
                    rows.append([
                        Paragraph(cls._sanitize(issue.get("severity", "unspecified")).upper(), body),
                        Paragraph(cls._sanitize(issue.get("area") or issue.get("target") or "Unspecified"), body),
                        Paragraph(
                            f"<b>Problem:</b> {cls._sanitize(issue.get('problem') or issue.get('issue') or '')}<br/>"
                            f"<b>Evidence:</b> {cls._sanitize(issue.get('evidence') or '')}",
                            muted
                        ),
                        Paragraph(cls._sanitize(issue.get("suggestion") or issue.get("recommendation") or ""), muted),
                    ])
            table = Table(rows, colWidths=[65, 95, 205, 155], repeatRows=1)
            table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.35, BORDER),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(table)
        else:
            story.append(Paragraph("No critique issues were recorded by Agent 6.", muted))
        bullet_section("Genericity Checks", critique.get("genericity_checks", []))
        bullet_section("Audience Mismatch Warnings", critique.get("audience_mismatch", []))
        bullet_section("Contradictions", critique.get("contradictions", []))
        bullet_section("Revised Options", critique.get("revised_options", []))
        story.append(PageBreak())

        # ---------------------------------------------------------------------
        # 09 CONSISTENCY
        # ---------------------------------------------------------------------
        section("09", "Consistency Guardian", "Cross-stage coherence audit.")
        score = consistency.get("overall_consistency", consistency.get("overall_score"))
        score_text = f"{score}/100" if score is not None else "Not scored"
        story.append(Paragraph(
            f"<b>Overall Brand Coherence:</b> <font color='{SAGE.hexval()}' size='16'><b>{cls._sanitize(score_text)}</b></font>",
            body
        ))
        checks = consistency.get("checks", [])
        if checks:
            rows = [[
                Paragraph("<b>Area</b>", body),
                Paragraph("<b>Status</b>", body),
                Paragraph("<b>Reason</b>", body),
            ]]
            for check in checks:
                if isinstance(check, dict):
                    status = check.get("status")
                    if status is None and "pass" in check:
                        status = "pass" if check.get("pass") else "fail"
                    rows.append([
                        Paragraph(cls._sanitize(check.get("area") or check.get("element") or check.get("name") or "Check"), body),
                        Paragraph(cls._sanitize(status or "unspecified").upper(), body),
                        Paragraph(cls._sanitize(check.get("reason") or check.get("findings") or check.get("detail") or ""), muted),
                    ])
            table = Table(rows, colWidths=[150, 75, 295], repeatRows=1)
            table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.35, BORDER),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(table)
        bullet_section("Required Revisions", consistency.get("required_revisions", []))
        story.append(PageBreak())

        # ---------------------------------------------------------------------
        # 10 LAUNCH MESSAGING
        # ---------------------------------------------------------------------
        section("10", "Launch Messaging", "Final synthesis and ready-to-use communication assets.")
        landing = launch.get("landing_page") or launch.get("landing_page_copy") or {}
        social = launch.get("social") or launch.get("social_copy") or {}
        key_value_table([
            ("Brand name", launch.get("brand_name") or brand_name),
            ("Tagline", launch.get("tagline") or tagline),
            ("One-line pitch", launch.get("one_line_pitch") or "Not generated by the workflow."),
            ("Landing headline", landing.get("headline") if isinstance(landing, dict) else ""),
            ("Landing subheadline", landing.get("subheadline") if isinstance(landing, dict) else ""),
            ("Primary CTA", landing.get("cta") if isinstance(landing, dict) else ""),
        ])
        story.append(Paragraph("Instagram Launch Copy", h2))
        story.append(Paragraph(
            cls._sanitize(social.get("instagram") or "Not generated by the workflow."),
            body
        ))
        story.append(Paragraph("LinkedIn Launch Copy", h2))
        story.append(Paragraph(
            cls._sanitize(social.get("linkedin") or "Not generated by the workflow."),
            body
        ))
        story.append(Paragraph("Brand Voice Examples", h2))
        story.extend(bullets(launch.get("brand_voice_samples", [])))
        story.append(PageBreak())

        # ---------------------------------------------------------------------
        # 11 LAUNCH ANNOUNCEMENT + CHANNEL PLAYBOOK
        # ---------------------------------------------------------------------
        section("11", "Launch Execution Playbook", "How the generated messaging can be applied across the first launch touchpoints.")
        story.append(Paragraph("Launch Announcement", h2))
        story.append(Paragraph(
            cls._sanitize(launch.get("launch_message") or "Not generated by the workflow."),
            body
        ))
        story.append(Paragraph("Message Hierarchy", h2))
        hierarchy = [
            ("Problem", val(discovery, "problem", default="Not generated.")),
            ("Audience", ", ".join(
                str(s.get("segment")) for s in discovery.get("target_users", [])
                if isinstance(s, dict) and s.get("segment")
            ) or "Not generated."),
            ("Difference", ", ".join(str(x) for x in as_list(positioning.get("differentiators"))) or "Not generated."),
            ("Value", val(positioning, "value_proposition", default="Not generated.")),
            ("Next action", social.get("instagram") or landing.get("cta") or "Not generated."),
        ]
        key_value_table(hierarchy)
        story.append(Spacer(1, 12))
        story.append(Paragraph("Implementation Notes", h2))
        story.extend(bullets([
            "Use the approved brand name consistently across product, website, social profiles, and launch assets.",
            "Keep positioning and audience language stable while adapting copy length to each channel.",
            "Use the visual direction as a system: color, typography, composition, imagery, and symbols should reinforce the same strategic personality.",
            "Treat open questions, assumptions, and proof points as validation work rather than established market facts.",
        ]))
        story.append(PageBreak())

        # ---------------------------------------------------------------------
        # 12 DECISION RECORD
        # ---------------------------------------------------------------------
        section("12", "Decision Record & Validation Queue", "What is decided, what is inferred, and what still needs human validation.")
        story.append(Paragraph("User Decisions", h2))
        if selected:
            for key, value in selected.items():
                if key in {"last_revision"}:
                    continue
                story.append(Paragraph(
                    f"<b>{cls._sanitize(key)}:</b> {cls._sanitize(value)}",
                    body
                ))
        else:
            story.append(Paragraph("No explicit selection metadata was stored with this export.", muted))

        story.append(Paragraph("Validation Queue", h2))
        validation_items = []
        validation_items.extend([f"Discovery assumption: {x}" for x in as_list(discovery.get("assumptions"))])
        validation_items.extend([f"Open question: {x}" for x in as_list(discovery.get("open_questions"))])
        validation_items.extend([f"Proof point to validate: {x}" for x in as_list(positioning.get("proof_points"))])
        validation_items.extend([f"Naming risk: {x}" for territory in as_list(naming.get("territories"))
                                 if isinstance(territory, dict)
                                 for candidate in as_list(territory.get("names"))
                                 if isinstance(candidate, dict)
                                 for x in as_list(candidate.get("risks"))])
        story.extend(bullets(validation_items, empty="No explicit validation queue was generated."))

        story.append(Spacer(1, 14))
        story.append(Paragraph(
            "This final section deliberately distinguishes generated strategy from validated reality. "
            "BrandForge's role is to create a coherent decision system; founders remain responsible for customer research, "
            "legal clearance, competitive verification, and final business decisions.",
            ParagraphStyle("BF_FinalNote", parent=body, fontName="Helvetica-Oblique", textColor=MUTED)
        ))

        doc.build(story, canvasmaker=NumberedCanvas)
        return buffer.getvalue()

